version: 2.1
jobs:
  build-push:
    docker:
      - image: touchbistro/alpine-node:10-build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: docker build --build-arg github_key=$GITHUB_RELEASE_SSH_KEY_BASE64 --target release . -t $AWS_ACCOUNT_ID.$ECR/shipit
      - run:
          name: Push
          command: |
            eval $(aws ecr get-login --region us-east-1 --no-include-email) &&
            docker push $AWS_ACCOUNT_ID.$ECR/shipit

workflows:
  version: 2
  build-push:
    jobs:
      - build-push:
         filters:
           branches:
             only: master