# See https://github.com/Shopify/shipit-engine/blob/master/docs/setup.md#updating-the-configsecretsyml for instructions

<%= ENV['RAILS_ENV'] %>:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  redis_url: <%= ENV['REDIS_URL'] %>
  host:
  github:
    app_id:
    installation_id:
    domain: # the domain name of your GitHub Enterprise instance, leave it empty if you use github.com
    bot_login: # optional
    webhook_secret:
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      -----END RSA PRIVATE KEY-----
    oauth:
      id:
      secret:
      team: # optional
